### ISSUE TITLE
Notification Panel turns white when scrolling

### ISSUE THREAD

**Issue by alex0091845** [evansuong/fouro-application#11]
### **Issue description**
On Android, when scrolling through notifications, any given notification panel turns white (as if pressed on) if the user begins scrolling/touching on it.

### **Expected result**
![expected notif panel](https://user-images.githubusercontent.com/45185445/99293528-a2670d00-27f7-11eb-8388-e52b3b562678.png)

---

### **Actual result**
![actual notif panel](https://user-images.githubusercontent.com/45185445/99293570-b4e14680-27f7-11eb-871e-0957a50c22ff.png)

**Comment by evansuong** [comment]
fixed: replaced touchableOpacity with touchableWihtouFeedback
